apiVersion: v1
kind: ConfigMap
metadata:
  name: webui-configmap
  labels:
    app: free5gc
data:
  webuicfg.yaml: |
    info:
      version: 1.0.3
      description: Docker-WebUI initial local configuration
    
    configuration:
      mongodb:
        name: free5gc
        url: mongodb://mongodb:27017
    
    # the kind of log output
    # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
    # ReportCaller: enable the caller report or not, value: true or false
    logger:
      enable: true # true or false
      level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      reportCaller: false # enable the caller report or not, value: true or false
